name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    #runs-on: ubuntu-latest
    runs-on: windows-latest
    #runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    #- name: Restore dependencies
    #  run: dotnet restore TestActions
    - name: Build
      run: dotnet build TestActions --no-restore
    - name: Test
      run: dotnet test TestActions --no-build --verbosity normal
