#  MIT License
#  Copyright (c) 2020 Lukas
#  https://github.com/LukBukkit/action-pr-limits

name: Limit PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  limit_main_pr:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: LukBukkit/action-pr-limits@v1.1.1
        with:
          allowlist: |
            develop
            hotfix-().{1}.*
